<?php
// composer require dompdf/dompdf で Dompdf をインストールしてください
require_once dirname(__DIR__, 2) . '/bootstrap.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// オプション設定
$options = new Options();
// デフォルトフォント
$options->set('defaultFont', 'sans-serif');
// HTML5タグを有効化
$options->set('isHtml5ParserEnabled', true);

// TODO: Dompdf インスタンス化
$dompdf = new Dompdf($options);

// HTMLコンテンツ
$html = '
<style>
    h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; }
    p { font-size: 14px; line-height: 1.6; }
</style>
<h1>Dompdf Sample</h1>
<p>Hello! This is a PDF generated by dompdf.</p>
';

// TODO: HTMLの読み込み: loadHtml()
$dompdf->loadHtml($html);

// TODO: 用紙サイズの設定: setPaper('A4', 'portrait') (A4サイズ・縦)
$dompdf->setPaper('A4', 'portrait');

// TODO: PDFのレンダリング: render()
$dompdf->render();

// TODO: 出力（ブラウザで表示）: stream("sample.pdf", ["Attachment" => false])
$dompdf->stream('sample.pdf', ["Attachment" => false]);
